### ISSUE TITLE
Is it possible to apply "retainedFileCountLimit" to archived log files

### ISSUE THREAD

**Issue by Ali94k** [cocowalla/serilog-sinks-file-archive#8]
I want to delete archived files after a while. How can this be achieved? Could you please advise on this

**Comment by ilkinmammadzada** [comment]
+1

**Comment by cocowalla** [comment]
In general, the assumption is that logs are being archived for some other process to hoover them up or otherwise deal with them.

On the face of it though, this seems like a reasonable thing to add - when I get a chance, I'll take a look at this and see if there are any complications or problems with it!

**Comment by cocowalla** [comment]
@EamonHetherton thanks for getting involved 😻

**Comment by cocowalla** [comment]
Closed by #9

**Comment by alex-pashkov97** [comment]
Hey, any updates when it will be released? I could really use this feature. Thanks in advance

**Comment by cocowalla** [comment]
@alex-pashkov97 sorry, I totally forgot this feature wasn't on NuGet yet! I'll try to get it published tomorrow.

**Comment by cocowalla** [comment]
@alex-pashkov97 Done!

https://www.nuget.org/packages/Serilog.Sinks.File.Archive/1.0.2
